### ISSUE TITLE
В классе GameStore не реализован метод Getter для словаря Map<String, Integer> playedTime.

### ISSUE THREAD

**Issue by AEryushova** [LSOrlova/javaqa-team-diplom#10]
# Описание
В классе GameStore не реализован метод Getter для для словаря Map< String, Integer > playedTime.
Метод Getter необходим в классе GameStoreTest для тестирования кода.

# Локализация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/GameStore.java#L12-L17

# Шаги воспроизведения :

1. Открыть  [код программы](https://github.com/LSOrlova/javaqa-team-diplom/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA. 
2. Открыть поле  private Map< String, Integer > playedTime 

*Ожидаемый результат:* Создан метод Getter для словаря Map< String, Integer > playedTime.
*Фактический результат:* Метод Getter отсутствует.

# Скриншот
[![image.png](https://i.postimg.cc/kMcMfnjt/image.png)](https://postimg.cc/CdRVKVpF)

# Окружение
- Операционная система : Windows 10 10.0
- IDE :  IntelliJ IDEA 2022.2.4 (Community Edition)
- Java : OpenJDK 11

**Comment by LSOrlova** [comment]
Сделано локально

**Comment by LSOrlova** [comment]
Не является багом. нет необходимости в Getter-е. Используем только в классе, где создан. Для тестов не используем в итоге
