### ISSUE TITLE
В классе GameStore метод addPlayTime не суммирует количество времени, которое игрок провел за игрой с прошлым значением.

### ISSUE THREAD

**Issue by AEryushova** [LSOrlova/javaqa-team-diplom#11]
# Описание
В классе GameStore метод addPlayTime не суммирует количество времени, которое игрок провел за игрой с прошлым значением. Если такой игрок уже есть в словаре Map< String, Integer > playedTime метод addPlayTime записывает прежнее значение времени (не суммирует к нему новое).

# Локализация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/GameStore.java#L48

# Шаги воспроизведения :

1. Открыть  [код программы](https://github.com/LSOrlova/javaqa-team-diplom/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA. 
2. Открыть тело метода addPlayTime.

*Ожидаемый результат:* Метод addPlayTime суммирует количество времени, которое игрок провел за игрой с прошлым значением и записывает в словарь.
*Фактический результат:* Метод addPlayTime записывает прежнее значение времени в словарь.
# Скриншот
[![image.png](https://i.postimg.cc/mZnwtFMb/image.png)](https://postimg.cc/vDW9KT3j)

# Окружение
- Операционная система : Windows 10 10.0
- IDE :  IntelliJ IDEA 2022.2.4 (Community Edition)
- Java : OpenJDK 11

**Comment by LSOrlova** [comment]
Исправлено локально
