### ISSUE TITLE
В классе GameStore метод getSumPlayedTime не суммирует общее количество времени всех игроков

### ISSUE THREAD

**Issue by AEryushova** [LSOrlova/javaqa-team-diplom#12]
# Описание
В классе GameStore метод getSumPlayedTime не суммирует общее количество времени всех игроков, а возвращает 0.

# Локализация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения :

1. Открыть  [код программы](https://github.com/LSOrlova/javaqa-team-diplom/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA. 
2. Открыть метод getSumPlayedTime .

*Ожидаемый результат:* Метод getSumPlayedTime суммирует общее количество времени всех игроков и возвращает результат.
*Фактический результат:* Метод getSumPlayedTime возвращает 0.
# Скриншот
[![image.png](https://i.postimg.cc/gcLV2CLx/image.png)](https://postimg.cc/grdXMBDp)

# Окружение
- Операционная система : Windows 10 10.0
- IDE :  IntelliJ IDEA 2022.2.4 (Community Edition)
- Java : OpenJDK 11

**Comment by LSOrlova** [comment]
FIxed
