### ISSUE TITLE
В классе GameStore метод getMostPlayer ведет поиск имени игрока, который больше всего играл в игры каталога не с 0

### ISSUE THREAD

**Issue by AEryushova** [LSOrlova/javaqa-team-diplom#13]
# Описание
В классе GameStore метод getMostPlayer ведет поиск имени игрока, который больше всего играл в игры каталога не с 0, а с 1.

# Локализация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/GameStore.java#L59

# Шаги воспроизведения :

1. Открыть  [код программы](https://github.com/LSOrlova/javaqa-team-diplom/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA. 
2. Открыть метод getMostPlayer.
3. Обратить внимание на переменную int mostTime.

*Ожидаемый результат:* Переменной int mostTime присвоено значение 0.
*Фактический результат:*Переменной int mostTime присвоено значение 1.

# Скриншот
[![image.png](https://i.postimg.cc/RCXVHhrh/image.png)](https://postimg.cc/14VQx931)

# Окружение
- Операционная система : Windows 10 10.0
- IDE :  IntelliJ IDEA 2022.2.4 (Community Edition)
- Java : OpenJDK 11

**Comment by LSOrlova** [comment]
Сделано локально
