### ISSUE TITLE
Класс Player, метод Play: метод не добавляет проигранное время

### ISSUE THREAD

**Issue by LSOrlova** [LSOrlova/javaqa-team-diplom#14]
### Описание
Класс Player, метод Play: метод всегда возвращает суммарное количество часов, проигранное в эту игру, без добавления проигранного времени

#### Локация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/Player.java#L33

#### Шаги воспроизведения
Открыть код программы в IDEA
Открыть класс Player
Открыть метод Play

#### Фактический результат:
Класс Player, метод Play: метод всегда возвращает суммарное количество часов, проигранное в эту игру, без добавления проигранного времени

#### Ожидаемый результат:
Необходимо обновить значения в мапе игрока, добавив проигранное количество часов

#### Скрин:
![Снимок (4)](https://user-images.githubusercontent.com/118666858/218088137-ac0bbf55-861e-4bba-9a6e-539356086df9.PNG)

#### Окружение
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AEryushova** [comment]
Done
