### ISSUE TITLE
Ошибка "Assertion failed error" при запуске теста shouldSumGenreIfOneGame

### ISSUE THREAD

**Issue by LSOrlova** [LSOrlova/javaqa-team-diplom#2]
### Описание:
Тест shouldSumGenreIfOneGame из "PlayerTest" выполняется с ошибкой "Assertion failed error"

#### Локация дефекта

https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/test/java/ru/netology/PlayerTest.java#L8

#### Шаги воспроизведения:
1. Открыть код программы в IDEA
2. Открыть класс PlayerTest
3. Запустить тест shouldSumGenreIfOneGame

#### Фактический результат:
Выдается ошибка "assertion failed error" (ожидаемый результат не соответствует фактическому)
Метод sumGenre отрабатывает неверно

#### Ожидаемый результат:
Фактический результат равен ожидаемому. Тест выполнен без ошибок (проходит успешно)

**Скрин:**
![player_test_exp_not_equal_act](https://user-images.githubusercontent.com/118666858/216808111-463f39e7-f2f3-46a4-8382-a2cbafbebe8c.jpg)

#### Oкружение:
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AEryushova** [comment]
Done
