### ISSUE TITLE
Класс Player,  метод InstallGame: нет проверки, если игра уже добавлена в каталог

### ISSUE THREAD

**Issue by LSOrlova** [LSOrlova/javaqa-team-diplom#3]
### Описание
Класс Player, InstallGame: нет проверки, если игра уже добавлена в каталог. Если игра уже была, данные будут перезаписаны некорректно

#### Локация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/Player.java#L23-L25

#### Шаги воспроизведения

1. Открыть код программы в IDEA
2. Открыть класс Player
3. Открыть метод InstallGame

#### Фактический результат:
в методе не реализована проверка, была ли игра ранее добавлена  в каталог игрока. 

#### Ожидаемый результат:
Игра добавляется игроку только в случае, если ранее не была добавлена. 
В случае, если игра уже была, никаких изменений происходить не должно.

**Скрин:**

![no_check_game_exist](https://user-images.githubusercontent.com/118666858/216817574-00b5032d-015d-48d5-be64-64c5f62778fe.jpg)

#### Окружение
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AEryushova** [comment]
Done
