### ISSUE TITLE
Класс Player, метод sumGenre: в условии else сумма проигранного времени всегда равна 0

### ISSUE THREAD

**Issue by LSOrlova** [LSOrlova/javaqa-team-diplom#4]
### Описание
Класс Player, метод sumGenre: в условии else сумма проигранного времени всегда равна 0

#### Локация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/Player.java#L50-L51

#### Шаги воспроизведения

1. Открыть код программы в IDEA
2. Открыть класс Player
3. Открыть метод sumGenre

#### Фактический результат:
В условии else суммируемое время всегда равно 0

#### Ожидаемый результат:
Время должно суммироваться с уже проигранным ранее в игру этого же жанра этим игроком

#### Скрин:

![sum_null](https://user-images.githubusercontent.com/118666858/216818466-4cd40098-9ead-4262-bbe9-cec4c2019d11.jpg)

#### Окружение
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AEryushova** [comment]
Done
