### ISSUE TITLE
Класс Player, метод mostPlayerByGenre: метод всегда возвращает null

### ISSUE THREAD

**Issue by LSOrlova** [LSOrlova/javaqa-team-diplom#5]
### Описание
Класс Player, метод mostPlayerByGenre: метод всегда возвращает null

#### Локация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/Player.java#L60

#### Шаги воспроизведения
Открыть код программы в IDEA
Открыть класс Player
Открыть метод mostPlayerByGenre

#### Фактический результат:
Класс Player, метод mostPlayerByGenre: метод всегда возвращает null

#### Ожидаемый результат:
Метод принимает жанр и возвращает игру этого жанра, в которую играли больше всего.
Только если в игры этого жанра не играли, возвращается null

#### Скрин:

![return_null](https://user-images.githubusercontent.com/118666858/216818875-4f37f384-9c89-4e45-a50a-bfc63f48e899.jpg)

**Окружение**
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AEryushova** [comment]
Done
