### ISSUE TITLE
В классе GameStore метод containsGame проверяет наличие игры в каталоге не с 1 ячейки.

### ISSUE THREAD

**Issue by AEryushova** [LSOrlova/javaqa-team-diplom#7]
# Описание
В классе GameStore метод containsGame проверяет наличие игры в каталоге не с 1 ячейки ( с индексом 0). 
В переменной int i в теле цикла указана 1, вместо 0.

# Локализация дефекта
https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения :

1. Открыть  [код программы](https://github.com/LSOrlova/javaqa-team-diplom/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA. 
2. Открыть метод containsGame.
3. Обратить внимание на тело цикла for с переменной int i.

*Ожидаемый результат:* Цикл в методе containsGame начинает работать с 0. Переменная int i равна 0.
*Фактический результат:* Цикл в методе containsGame начинает работать с 1. Переменная int i равна 1.

# Скриншот
[![image.png](https://i.postimg.cc/C1ww7QWS/image.png)](https://postimg.cc/R3brVXSD)

# Окружение
- Операционная система : Windows 10 10.0
- IDE :  IntelliJ IDEA 2022.2.4 (Community Edition)
- Java : OpenJDK 11

**Comment by LSOrlova** [comment]
Сделано локально
