### ISSUE TITLE
В классе GameStore метод publishGame перед добавлением игры в список List<Game> games не проверяет наличие игры в каталоге через функцию containsGame. 

### ISSUE THREAD

**Issue by AEryushova** [LSOrlova/javaqa-team-diplom#8]
# Описание
В классе GameStore метод publishGame перед добавлением игры в список List< Game > games не проверяет наличие игры в каталоге через функцию containsGame. В методе publishGame не добавлена функция containsGame.

# Локализация дефекта: https://github.com/LSOrlova/javaqa-team-diplom/blob/4ff97a9c513a9d0fa8a065b92f85efa90dc3e0eb/src/main/java/ru/netology/GameStore.java#L19-L39

# Шаги воспроизведения :

1. Открыть  [код программы](https://github.com/LSOrlova/javaqa-team-diplom/blob/main/src/main/java/ru/netology/GameStore.java) в IDEA. 
2. Открыть метод publishGame .
3. Открыть метод containsGame.

# *Ожидаемый результат:* 
После создания объекта game в методе publishGame вызывается метод containsGame, который проверяет наличие игры в каталоге. В случае false, игра добавляется в список List< Game > games и возвращается методом publishGame. 

# *Фактический результат:* 
После создания объекта game в методе publishGame игра добавляется в список List< Game > games и возвращается методом publishGame. Функция containsGame реализована отдельно и не используется в publishGame.

# Скриншот
[![image.png](https://i.postimg.cc/6QBMWkSk/image.png)](https://postimg.cc/cv5RTbdh)

# Окружение
- Операционная система : Windows 10 10.0
- IDE :  IntelliJ IDEA 2022.2.4 (Community Edition)
- Java : OpenJDK 11

**Comment by LSOrlova** [comment]
Исправлено локально
